-- MySQL Script generated by MySQL Workbench
-- Thu May 21 08:35:02 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo_090207_m1_m2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo_090207_m1_m2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_090207_m1_m2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `demo_090207_m1_m2` ;

-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`counterparty_role_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`counterparty_role_types` (
  `role_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_type_id`),
  UNIQUE INDEX `uk_role_types_role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Типы ролей контрагента: заказчик, продавец, изготовитель';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`counterparties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`counterparties` (
  `counterparty_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `inn` VARCHAR(12) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`counterparty_id`),
  UNIQUE INDEX `uk_counterparties_inn` (`inn` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Контрагенты предприятия';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`counterparty_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`counterparty_roles` (
  `counterparty_role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `counterparty_id` INT UNSIGNED NOT NULL,
  `role_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`counterparty_role_id`, `counterparty_id`, `role_type_id`),
  UNIQUE INDEX `uk_counterparty_roles_pair` (`counterparty_id` ASC, `role_type_id` ASC) VISIBLE,
  INDEX `idx_counterparty_roles_counterparty` (`counterparty_id` ASC) VISIBLE,
  INDEX `idx_counterparty_roles_role_type` (`role_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_counterparty_roles_counterparty`
    FOREIGN KEY (`counterparty_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparties` (`counterparty_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_counterparty_roles_role_type`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparty_role_types` (`role_type_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Связь контрагентов с их ролями';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`products` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `uk_products_product_name` (`product_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Готовая продукция';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`materials` (
  `material_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`material_id`),
  UNIQUE INDEX `uk_materials_material_name` (`material_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Материалы для производства';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`material_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`material_prices` (
  `material_price_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `material_id` INT UNSIGNED NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`material_price_id`),
  UNIQUE INDEX `uk_material_prices_material_date` (`material_id` ASC, `date_from` ASC) VISIBLE,
  INDEX `idx_material_prices_material` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_material_prices_material`
    FOREIGN KEY (`material_id`)
    REFERENCES `demo_090207_m1_m2`.`materials` (`material_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'История цен материалов';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`product_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`product_prices` (
  `product_price_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`product_price_id`),
  UNIQUE INDEX `uk_product_prices_product_date` (`product_id` ASC, `date_from` ASC) VISIBLE,
  INDEX `idx_product_prices_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_prices_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `demo_090207_m1_m2`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'История цен продукции';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`specifications` (
  `specification_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `specification_name` VARCHAR(255) NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `manufacturer_id` INT UNSIGNED NOT NULL,
  `output_quantity` DECIMAL(15,3) NOT NULL DEFAULT 1.000,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`specification_id`),
  UNIQUE INDEX `uk_specifications_name_product_manufacturer` (`specification_name` ASC, `product_id` ASC, `manufacturer_id` ASC) VISIBLE,
  INDEX `idx_specifications_product` (`product_id` ASC) VISIBLE,
  INDEX `idx_specifications_manufacturer` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_specifications_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `demo_090207_m1_m2`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_specifications_manufacturer`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparties` (`counterparty_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Спецификации производства продукции';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`specification_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`specification_materials` (
  `specification_material_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `specification_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  `material_quantity` DECIMAL(15,3) NOT NULL,
  PRIMARY KEY (`specification_material_id`, `specification_id`, `material_id`),
  UNIQUE INDEX `uk_specification_materials_pair` (`specification_id` ASC, `material_id` ASC) VISIBLE,
  INDEX `idx_specification_materials_specification` (`specification_id` ASC) VISIBLE,
  INDEX `idx_specification_materials_material` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_specification_materials_specification`
    FOREIGN KEY (`specification_id`)
    REFERENCES `demo_090207_m1_m2`.`specifications` (`specification_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_specification_materials_material`
    FOREIGN KEY (`material_id`)
    REFERENCES `demo_090207_m1_m2`.`materials` (`material_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Нормы расхода материалов по спецификациям';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`productions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`productions` (
  `production_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `production_number` VARCHAR(50) NOT NULL,
  `production_date` DATE NOT NULL,
  `specification_id` INT UNSIGNED NOT NULL,
  `manufacturer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`production_id`),
  UNIQUE INDEX `uk_productions_number` (`production_number` ASC) VISIBLE,
  INDEX `idx_productions_specification` (`specification_id` ASC) VISIBLE,
  INDEX `idx_productions_manufacturer` (`manufacturer_id` ASC) VISIBLE,
  INDEX `idx_productions_date` (`production_date` ASC) VISIBLE,
  CONSTRAINT `fk_productions_specification`
    FOREIGN KEY (`specification_id`)
    REFERENCES `demo_090207_m1_m2`.`specifications` (`specification_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productions_manufacturer`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparties` (`counterparty_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Выпуски производства';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`production_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`production_materials` (
  `production_material_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `production_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(15,3) NOT NULL,
  PRIMARY KEY (`production_material_id`, `production_id`, `material_id`),
  UNIQUE INDEX `uk_production_materials_pair` (`production_id` ASC, `material_id` ASC) VISIBLE,
  INDEX `idx_production_materials_production` (`production_id` ASC) VISIBLE,
  INDEX `idx_production_materials_material` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_production_materials_production`
    FOREIGN KEY (`production_id`)
    REFERENCES `demo_090207_m1_m2`.`productions` (`production_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_production_materials_material`
    FOREIGN KEY (`material_id`)
    REFERENCES `demo_090207_m1_m2`.`materials` (`material_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Фактически списанные материалы производства';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`production_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`production_items` (
  `production_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `production_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(15,3) NOT NULL,
  PRIMARY KEY (`production_item_id`, `production_id`, `product_id`),
  UNIQUE INDEX `uk_production_items_pair` (`production_id` ASC, `product_id` ASC) VISIBLE,
  INDEX `idx_production_items_production` (`production_id` ASC) VISIBLE,
  INDEX `idx_production_items_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_production_items_production`
    FOREIGN KEY (`production_id`)
    REFERENCES `demo_090207_m1_m2`.`productions` (`production_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_production_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `demo_090207_m1_m2`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Выпущенная продукция производства';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`customer_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`customer_orders` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(50) NOT NULL,
  `order_date` DATE NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `seller_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `uk_customer_orders_number` (`order_number` ASC) VISIBLE,
  INDEX `idx_customer_orders_customer` (`customer_id` ASC) VISIBLE,
  INDEX `idx_customer_orders_seller` (`seller_id` ASC) VISIBLE,
  INDEX `idx_customer_orders_date` (`order_date` ASC) VISIBLE,
  CONSTRAINT `fk_customer_orders_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparties` (`counterparty_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_orders_seller`
    FOREIGN KEY (`seller_id`)
    REFERENCES `demo_090207_m1_m2`.`counterparties` (`counterparty_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Заказы покупателей';


-- -----------------------------------------------------
-- Table `demo_090207_m1_m2`.`customer_order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo_090207_m1_m2`.`customer_order_items` (
  `order_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(15,3) NOT NULL,
  `sale_price` DECIMAL(15,2) NOT NULL,
  `line_amount` DECIMAL(15,2) GENERATED ALWAYS AS (ROUND(`quantity` * `sale_price`, 2)) STORED,
  PRIMARY KEY (`order_item_id`, `order_id`, `product_id`),
  UNIQUE INDEX `uk_customer_order_items_pair` (`order_id` ASC, `product_id` ASC) VISIBLE,
  INDEX `idx_customer_order_items_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_customer_order_items_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_order_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `demo_090207_m1_m2`.`customer_orders` (`order_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_order_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `demo_090207_m1_m2`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Позиции заказов покупателей';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
