<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SQL\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\AdminDashboardForm.Designer.cs">
      <DependentUpon>AdminDashboardForm.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\UserDashboardForm.Designer.cs">
      <DependentUpon>UserDashboardForm.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\UserEditForm.Designer.cs">
      <DependentUpon>UserEditForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\AdminDashboardForm.resx">
      <DependentUpon>AdminDashboardForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\UserDashboardForm.resx">
      <DependentUpon>UserDashboardForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Forms\UserEditForm.resx">
      <DependentUpon>UserEditForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
